# Generated by Django 4.2.2 on 2024-06-07 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_award_base_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='base_award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='awards', to='awards.baseaward'),
        ),
    ]
