# Generated by Django 4.2.2 on 2024-06-07 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_alter_award_base_award'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='user_id',
            new_name='user',
        ),
    ]
